# Generated by Django 3.0.14 on 2021-09-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('ideas', '0002_idea_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='categories.Category', verbose_name='Categories'),
        ),
    ]
