# Generated by Django 3.0.14 on 2021-09-18 17:05

from django.db import migrations

def copy_categories(apps, schema_editor):
	Idea = apps.get_model("ideas", "Idea")
	for idea in Idea.objects.all():
		if idea.category:
			idea.categories.add("idea.category")

class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_categories'),
    ]

    operations = [
		migrations.RunPython(copy_categories),
    ]
